name: CMake

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: read

    strategy:
      matrix:
        include:
          - target: win_x64
            vs_arch: x64
            runner: windows-latest
            cmake_args: ''
            cmake_configs: 'Release;Debug'
            workdir: C:/Workspace
            qtbase_config: '
                -DFEATURE_optimize_size=on 
                -DFEATURE_dbus=off 
                -DFEATURE_printsupport=off 
                -DFEATURE_widgets=off 
                -DFEATURE_xml=off 
                -DFEATURE_topleveldomain=off 
                -DFEATURE_androiddeployqt=off 
                -DFEATURE_gif=off 
                -DFEATURE_ico=off 
                -DFEATURE_texthtmlparser=off 
                -DFEATURE_textmarkdownreader=on 
                -DFEATURE_textmarkdownwriter=off 
                -DFEATURE_textodfwriter=off 
                -DFEATURE_cssparser=off 
                -DFEATURE_opengl=off 
                -DFEATURE_dynamicgl=off 
                -DFEATURE_sql_odbc=off 
                -DFEATURE_direct2d=off 
                -DFEATURE_directwrite=off'

            qtdeclarative_config: '
                -DFEATURE_quickcontrols2_fusion=OFF 
                -DFEATURE_quickcontrols2_imagine=OFF 
                -DFEATURE_quickcontrols2_ios=OFF 
                -DFEATURE_quickcontrols2_macos=OFF 
                -DFEATURE_quickcontrols2_material=OFF 
                -DFEATURE_quickcontrols2_universal=OFF 
                -DFEATURE_quickcontrols2_windows=OFF'

          - target: linux_x64
            runner: ubuntu-latest
            container: ghcr.io/desk5/ubuntu18-buildenv:latest

            cmake_args: "-DCMAKE_TOOLCHAIN_FILE=/tmp/gcc8.cmake"
            cmake_configs: 'Release'
            workdir: /workspace
            qtbase_config: '
                -DFEATURE_cxx17_filesystem=off
                -DFEATURE_optimize_size=on 
                -DFEATURE_printsupport=off 
                -DFEATURE_widgets=off 
                -DFEATURE_xml=off 
                -DFEATURE_topleveldomain=off 
                -DFEATURE_androiddeployqt=off 
                -DFEATURE_gif=off 
                -DFEATURE_ico=off 
                -DFEATURE_texthtmlparser=off 
                -DFEATURE_textmarkdownreader=on 
                -DFEATURE_textmarkdownwriter=off 
                -DFEATURE_textodfwriter=off 
                -DFEATURE_cssparser=off 
                -DFEATURE_sql_odbc=off
                -DFEATURE_sql_mysql=off
                -DFEATURE_sql_psql=off
                -DFEATURE_vnc=off
                -DFEATURE_linuxfb=off
                -DFEATURE_eglfs=off'
            qtdeclarative_config: '
                -DFEATURE_quickcontrols2_fusion=OFF 
                -DFEATURE_quickcontrols2_imagine=OFF 
                -DFEATURE_quickcontrols2_ios=OFF 
                -DFEATURE_quickcontrols2_macos=OFF 
                -DFEATURE_quickcontrols2_material=OFF 
                -DFEATURE_quickcontrols2_universal=OFF 
                -DFEATURE_quickcontrols2_windows=OFF'

          - target: mac_x64
            runner: macos-latest
            cmake_args: '"-DCMAKE_OSX_ARCHITECTURES=x86_64"'
            cmake_configs: 'Release'
            workdir: /Users/runner/workspace
            qtbase_config: '
                -DFEATURE_optimize_size=on 
                -DFEATURE_dbus=off 
                -DFEATURE_printsupport=off 
                -DFEATURE_widgets=off 
                -DFEATURE_xml=off 
                -DFEATURE_topleveldomain=off 
                -DFEATURE_androiddeployqt=off 
                -DFEATURE_gif=off 
                -DFEATURE_ico=off 
                -DFEATURE_texthtmlparser=off 
                -DFEATURE_textmarkdownreader=on 
                -DFEATURE_textmarkdownwriter=off 
                -DFEATURE_textodfwriter=off 
                -DFEATURE_cssparser=off 
                -DINPUT_opengl=no
                -DFEATURE_sql_odbc=off
                -DFEATURE_sql_mysql=off
                -DFEATURE_sql_psql=off
                -DFEATURE_vnc=off'
            qtdeclarative_config: '
                -DFEATURE_quickcontrols2_fusion=OFF 
                -DFEATURE_quickcontrols2_imagine=OFF 
                -DFEATURE_quickcontrols2_ios=OFF 
                -DFEATURE_quickcontrols2_macos=OFF 
                -DFEATURE_quickcontrols2_material=OFF 
                -DFEATURE_quickcontrols2_universal=OFF 
                -DFEATURE_quickcontrols2_windows=OFF'

          - target: mac_arm64
            # The runner is x64 and we are building for ARM
            # We need to "cross-compile" Qt. This requires a set of "host tools" from a
            # native Intel build. We install stock Qt for this. Setting CMAKE_SYSTEM_NAME
            # triggers cross-compilation mode.
            cross_qt_host: 'mac'
            cross_qt_version: '6.5.2'
            cross_qt_arch: 'clang_64'
            cross_qt_path: '/Users/runner/work/qt/Qt/6.5.2/macos'
            runner: macos-latest
            cmake_args: '"-DCMAKE_OSX_ARCHITECTURES=arm64" -DCMAKE_SYSTEM_NAME=Darwin -DQT_FORCE_BUILD_TOOLS=on -DQT_HOST_PATH=/Users/runner/work/qt/Qt/6.5.2/macos'
            cmake_configs: 'Release'
            workdir: /Users/runner/workspace
            qtbase_config: '
                -DFEATURE_optimize_size=on 
                -DFEATURE_dbus=off 
                -DFEATURE_printsupport=off 
                -DFEATURE_widgets=off 
                -DFEATURE_xml=off 
                -DFEATURE_topleveldomain=off 
                -DFEATURE_androiddeployqt=off 
                -DFEATURE_gif=off 
                -DFEATURE_ico=off 
                -DFEATURE_texthtmlparser=off 
                -DFEATURE_textmarkdownreader=on 
                -DFEATURE_textmarkdownwriter=off 
                -DFEATURE_textodfwriter=off 
                -DFEATURE_cssparser=off 
                -DINPUT_opengl=no
                -DFEATURE_sql_odbc=off
                -DFEATURE_sql_mysql=off
                -DFEATURE_sql_psql=off
                -DFEATURE_vnc=off'
            qtdeclarative_config: '
                -DFEATURE_quickcontrols2_fusion=OFF 
                -DFEATURE_quickcontrols2_imagine=OFF 
                -DFEATURE_quickcontrols2_ios=OFF 
                -DFEATURE_quickcontrols2_macos=OFF 
                -DFEATURE_quickcontrols2_material=OFF 
                -DFEATURE_quickcontrols2_universal=OFF 
                -DFEATURE_quickcontrols2_windows=OFF'

      fail-fast: false

    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container }}
    env:
      Qt6_DIR: ${{matrix.workdir}}/Qt6-desk5/${{matrix.target}}
      BUILD_DIR_BASE: ${{matrix.workdir}}/build

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Setup VS Dev Environment
      if: runner.os == 'Windows'
      uses: egor-tensin/vs-shell@v2
      with:
        arch: ${{ matrix.vs_arch }}

    - name: Setup GCC8 toolchain
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 'set(CMAKE_C_COMPILER gcc-8)
              set(CMAKE_CXX_COMPILER g++-8)
              set(CMAKE_CXX_STANDARD_LIBRARIES -lstdc++fs)' > /tmp/gcc8.cmake

    - name: Install Homebrew dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: brew install ninja

    - name: Install Host Qt for cross-compilation
      uses: jurplel/install-qt-action@v3
      if: matrix.cross_qt_host
      with:
        version: ${{matrix.cross_qt_version}}
        host: ${{matrix.cross_qt_host}}
        target: 'desktop'
        arch: ${{matrix.cross_qt_arch}}
        archives: 'qtbase qtdeclarative'
        modules: 'qtshadertools'
        add-tools-to-path: false
        set-env: false
        cache: true

    # We depend on a modified syncqt, so we need to replace it in the downloaded host-Qt build
    # This is designed to support mac_arm64 builds on mac_x64 hosts.
    - name: Rebuild Host SyncQt for cross-compilation
      if: matrix.cross_qt_host
      shell: bash
      run: g++ -o ${{matrix.cross_qt_path}}/libexec/syncqt -include $(find ${{matrix.cross_qt_path}} -name qconfig.h) --std=c++17 qtbase/src/tools/syncqt/main.cpp

    - name: Configure QtBase
      shell: bash
      run: >
          cmake -S qtbase -B "${BUILD_DIR_BASE}-qtbase"
          "-DCMAKE_INSTALL_PREFIX=${{env.Qt6_DIR}}"
          -G "Ninja Multi-Config"
          "-DCMAKE_CONFIGURATION_TYPES=${{matrix.cmake_configs}}"
          ${{matrix.cmake_args}}
          ${{matrix.qtbase_config}}

    - name: Build QtBase
      shell: bash
      run: cmake --build "${BUILD_DIR_BASE}-qtbase" --parallel

    - name: Install QtBase
      shell: bash
      run: ninja -C "${BUILD_DIR_BASE}-qtbase" install

    - name: Configure QtShaderTools
      shell: bash
      run: cmake -S qtshadertools -B "${BUILD_DIR_BASE}-qtshadertools" "-DCMAKE_INSTALL_PREFIX=${{env.Qt6_DIR}}" -G Ninja ${{matrix.cmake_args}} -DCMAKE_BUILD_TYPE=Release
    
    - name: Build QtShaderTools
      shell: bash
      run: cmake --build "${BUILD_DIR_BASE}-qtshadertools" --parallel
    
    - name: Install QtShaderTools
      shell: bash
      run: ninja -C "${BUILD_DIR_BASE}-qtshadertools" install

    - name: Configure QtDeclarative
      shell: bash
      run: >
          cmake -S qtdeclarative -B "${BUILD_DIR_BASE}-qtdeclarative"
          "-DCMAKE_INSTALL_PREFIX=${{env.Qt6_DIR}}"
          -G "Ninja Multi-Config"
          "-DCMAKE_CONFIGURATION_TYPES=${{matrix.cmake_configs}}"
          ${{matrix.cmake_args}}
          ${{matrix.qtdeclarative_config}}

    - name: Build QtDeclarative
      shell: bash
      run: cmake --build "${BUILD_DIR_BASE}-qtdeclarative" --parallel

    - name: Install QtDeclarative
      shell: bash
      run: ninja -C "${BUILD_DIR_BASE}-qtdeclarative" install

    - name: Remove __qt_platform_requires_host_info_package flag from build
      if: matrix.cross_qt_host
      shell: bash
      run: perl -pi -e 's/(?<=__qt_platform_requires_host_info_package )"TRUE"/"FALSE"/' ${{env.Qt6_DIR}}/lib/cmake/Qt6/Qt6Dependencies.cmake

    - name: Archive Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: '${{github.workspace}}/qt6-${{github.ref_name}}-${{matrix.target}}.zip'
        directory: ${{matrix.workdir}}
        path: Qt6-desk5
        exclusions: '*.pdb'
        recursive_exclusions: '*.pdb'

    - name: Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: qt6-${{github.ref_name}}-${{matrix.target}}.zip
